spring.application.name=task-management-system

# Server
server.port=${PORT:8080}

# DATABASE (PostgreSQL - Supabase)
spring.datasource.url=jdbc:postgresql://db.hxiwvlzzcimhqgxahgam.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=R8n!t/PaF5Ff8Mf
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expirationMs=900000
app.jwt.refreshExpirationMs=604800000

# JPA
spring.jpa.open-in-view=false


# R8n!t/PaF5Ff8Mf